name: "guziohub"

secrets:
  bot_minecraft:
    file: "./secrets/bot_minecraft.txt"
  mc_seed:
    file: "./secrets/mc_seed.txt"
  pgpass:
    file: "./secrets/pgpass.txt"
  ncappkey:
    file: "./secrets/ncappkey.txt"

services:
  web:
    image: caddy:alpine
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ./caddy/etc:/etc/caddy
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/placeholder-website:/srv:ro
      - ./nc:/var/www/html:ro
      - ../files/drive:/var/www/html/data:ro
    ports:
      - "80:80"
      - "443:443"
      - "80:80/udp"
      - "443:443/udp"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "127.0.0.1:2019/metrics"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
    environment:
      - TZ=Europe/Warsaw

  nextcloud:
    image: nextcloud:31-fpm-alpine
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
      ncapps:
        condition: service_healthy
    secrets:
      - pgpass
    volumes:
      - ./nc:/var/www/html
      - ../files/drive:/var/www/html/data
    environment:
      - TZ=Europe/Warsaw
      - NEXTCLOUD_TRUSTED_DOMAINS=drive.guziohub.ovh
      - OVERWRITEHOST=drive.guziohub.ovh
      - OVERWRITECLIURL=https://drive.guziohub.ovh
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES=172.16.0.0/24
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=10G
      - POSTGRES_HOST=pgdb
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgpass
      - NEXTCLOUD_ADMIN_USER=root
      - REDIS_HOST=redis
      - DOMAIN=drive.guziohub.ovh
      - NEXTCLOUD_VERSION=31-fpm-alpine
      - UID=1001
      - GID=1001

  imaginary:
    image: nextcloud/aio-imaginary:latest
    restart: unless-stopped
    expose:
      - "9000"
    depends_on:
      nextcloud:
        condition: service_started
    environment:
      - TZ=Europe/Warsaw
    cap_add:
      - SYS_NICE
    tmpfs:
      - /tmp

  nctasks:
    image: nextcloud:31-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./nc:/var/www/html
      - ../files/drive:/var/www/html/data
    entrypoint: /cron.sh
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - pgdb
      - redis
  
  ncapps:
    image: ghcr.io/nextcloud/nextcloud-appapi-dsp:release
    restart: unless-stopped
    secrets:
      - ncappkey
    environment:
      - NC_HAPROXY_PASSWORD_FILE=/run/secrets/ncappkey
      - TZ=Europe/Warsaw
    volumes:
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock
    privileged: true
  
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    
  pgdb:
    image: postgres:17-alpine
    restart: unless-stopped
    secrets:
      - pgpass
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgpass
      - TZ=Europe/Warsaw
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 15s
      interval: 30s
      retries: 3
      timeout: 5s
  
  minecraft:
    # Docker Config
    image: "itzg/minecraft-server:java21-graalvm"
    tty: true
    stdin_open: true
    volumes:
      - "../minecraft/server:/data"
      - "../minecraft/builds:/modpacks:ro"
    ports:
      - "25565:25565"
    #restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      start_period: 210s #3,5min
      interval: 3s
      retries: 40 #extra 2min
    secrets:
      - bot_minecraft
      - mc_seed
    # MC Config
    environment:
      # Modpack
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "/modpacks/[NAME].mrpack" # Placeholder. For now, mc-docker will try to load it, fail (because there'd be no such file) and (due to `restart: no`) not try again. If I ever run an MC server on this machine in the future, this (along with the restart policy) will of course have to be changed.
      # Minecraft stuff
      GUI: "FALSE"
      EULA: "TRUE"              #  Why are some bools upper-case...
      # Java stuff
      MEMORY: "18G"
      USE_AIKAR_FLAGS: "true"   #  ...and others lower-case? No fucking idea! I'm just following the docs, that's all.
      # Secrets
      CFG_BOT_TOKEN_FILE: "/run/secrets/bot_minecraft"
      CFG_SEED_FILE: "/run/secrets/mc_seed"
      # Desperatley trying to get Secrets to work
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      REPLACE_ENV_IN_PLACE: "true"
      REPLACE_ENV_DURING_SYNC: "true"
      # Misc
      TZ: "Europe/Warsaw"
      LOG_TIMESTAMP: "true"
      GID: "1001"  # My user group on the host machine
      UID: "1001"  # My user on the host machine
      MODRINTH_FORCE_SYNCHRONIZE: "true"
      DATAPACKS: "/data/datapacks"
      LEVEL: "world"